services:
  backend:
    container_name: superhero-backend
    build: 
      context: .
      dockerfile: Dockerfile.dev ## Use Dockerfile.prod for production
    env_file:
      - .env
    ports:
      - ${EXTERNAL_PORT}:${SERVER_PORT}
      - ${MONGO_PORT}:${MONGO_PORT} ## Port mapping if using MongoDB in local
    ## remove the volume mounting for production
    volumes:
      - ./:/app