version: '3.8'

services:
  backend:
    container_name: superhero-backend
    build:
      context: .
      dockerfile: Dockerfile.dev ## Use Dockerfile.prod for production
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${EXTERNAL_PORT}:${SERVER_PORT}


    ## remove the volume mounting for production
    volumes:
      - ./:/app

  db:
    container_name: superhero-db
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - superhero-db:/data/db
      - superhero-db-config:/data/configdb
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  superhero-db:
    name: superhero-db
  superhero-db-config:
    name: superhero-db-config