version: '3.8'

services:
  backend:
    container_name: superhero-backend
    build:
      context: .
      dockerfile: Dockerfile.dev ## Use Dockerfile.prod for production
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${EXTERNAL_PORT}:${SERVER_PORT}

    ## remove the volume mounting for production
    volumes:
      - ./:/app

  db:
    container_name: superhero-db
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - superhero:/data/db
      - superhero:/data/configdb

volumes:
  superhero:
    name: superhero-volume