basePath: /v1
definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        description: Omitted in response if empty
        type: string
      username:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Game server for Super Hero Game.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Super Hero Game MVC Backend
  version: "1.0"
paths:
  /users/signup:
    post:
      consumes:
      - application/json
      description: This endpoint allows a new user to register with the system.
      parameters:
      - description: User signup data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body or validation error
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Sign up a new user
      tags:
      - Users
swagger: "2.0"
